Added 7th GitHub Actions workflow

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -101,7 +101,32 @@
 
 
 
-name: Secrets Demo
+# name: Secrets Demo
+
+# on:
+#   push:
+#     branches:
+#       - main
+
+# jobs:
+#   secret-job:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Use secret safely
+#         run: |
+#           echo "Secret is available"
+#           echo "Length of secret: ${#MY_SECRET}"
+#         env:
+#           MY_SECRET: ${{ secrets.MY_SECRET }}
+
+
+
+
+
+
+
+name: Failure Demo
 
 on:
   push:
@@ -109,13 +134,20 @@ on:
       - main
 
 jobs:
-  secret-job:
+  failure-job:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Use secret safely
+      - name: Successful step
         run: |
-          echo "Secret is available"
-          echo "Length of secret: ${#MY_SECRET}"
-        env:
-          MY_SECRET: ${{ secrets.MY_SECRET }}
+          echo "This step succeeds"
+
+      - name: Intentional failure
+        run: |
+          echo "Failing now"
+          exit 1
+
+      - name: This will NOT run
+        run: |
+          echo "You will never see this"
+
