Added 8th GitHub Actions workflow

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -126,7 +126,37 @@
 
 
 
-name: Failure Demo
+# name: Failure Demo
+
+# on:
+#   push:
+#     branches:
+#       - main
+
+# jobs:
+#   failure-job:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Successful step
+#         run: |
+#           echo "This step succeeds"
+
+#       - name: Intentional failure
+#         run: |
+#           echo "Failing now"
+#           exit 1
+
+#       - name: This will NOT run
+#         run: |
+#           echo "You will never see this"
+
+
+
+
+
+
+name: Multi Job Pipeline
 
 on:
   push:
@@ -134,20 +164,26 @@ on:
       - main
 
 jobs:
-  failure-job:
+  build:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Successful step
+      - name: Build step
         run: |
-          echo "This step succeeds"
+          echo "Building application"
 
-      - name: Intentional failure
+  test:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Test step
         run: |
-          echo "Failing now"
-          exit 1
+          echo "Running tests"
 
-      - name: This will NOT run
+  deploy:
+    needs: test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Deploy step
         run: |
-          echo "You will never see this"
+          echo "Deploying application"
 
